version: '3'
services:
  web:
    image: home-hub-dashboard:latest
    build: .
    ports:
      - "8080:80"
    restart: always
    environment:
      - REMOOTIO_IP=${REMOOTIO_IP:-192.168.1.104}
      - REMOOTIO_PORT=${REMOOTIO_PORT:-887}
